### ISSUE TITLE
code lacks a proper project structure 

### ISSUE THREAD

**Issue by andy-d-palmer** [wengong-jin/chemprop#1]
The current code layout is pretty confusing with everything living in one directory.

Would it be useful refactor it so that this repository becomes a more standard [python project](https://stackoverflow.com/a/5998845)? 
Something like:
```
Chemprop/
|   demo/
|   |-- data/
|   |   |-- ___.csv
|   |--demo_runner.py
|
|-- chemprop/
|   |-- test/
|   |   |-- __init__.py
|   |   |-- test_todo.py
|   |   
|   |-- __init__.py
|   |-- mpn.py
|   |-- runers.py
|   |-- utils.py
|   |-- io.py
|
|-- setup.py
|-- README
|-- LICENCE
```
I'm happy to help out.

**Comment by swansonk14** [comment]
Thanks for the suggestion! The repo certainly has gotten a little messy as we've added more and more scripts. I just reorganized the code in roughly the structure you suggested. Please let us know how it looks and whether there's any other way we can improve it!
