### ISSUE TITLE
features_only failing?

### ISSUE THREAD

**Issue by joergkurtwegner** [wengong-jin/chemprop#10]
``
python train.py --gpu 0 --features_only --virtual_edges --ensemble_size 5 --num_folds 5 --data_path data/tox21.csv --dataset_type classification --save_dir checkpoints/tox21
``

causes
``
AttributeError: 'Namespace' object has no attribute 'features_dim'
``

**Comment by swansonk14** [comment]
The problem (which I realize now is not well documented) is that the `--features_only` flag requires that you also specify which features you would like to use, so you need to use it in conjunction with the `--features_generator <generator>` flag. For instance, if you would like to run a model using morgan fingerprints, you could use `--features_only --features_generator morgan`. We will add a better error message on the stable version of our repo here: https://github.com/swansonk14/chemprop.

**Comment by swansonk14** [comment]
There is now an assert statement in https://github.com/swansonk14/chemprop which checks for this case:

```python
if args.features_only:
    assert args.features_generator or args.features_path
```

**Comment by joergkurtwegner** [comment]
Thanks, works for me, we will look then at this code base as priority.
Thanks for letting me know.
