### ISSUE TITLE
prediction by default picking up all models in the directory

### ISSUE THREAD

**Issue by chupvl** [wengong-jin/chemprop#11]
Use case
DIR1/model1/
DIR1/model2/
DIR1/model3/
etc... 

predict.py automatically picking up all other directories (model1/2/3) while I defined to use only one for predictions, I suppose it should use only and only one directory to look for *.pt?
`python /home/user/git/chemprop/predict.py --test_path test.csv --preds_path test_preds.csv --checkpoint_path ./DIR1/model3/
`

**Comment by swansonk14** [comment]
The behavior of `--checkpoint_dir <dir>` is to walk the directory `<dir>` and to load all `*.pt` files it finds. It then uses all the models it finds as an ensemble to make predictions. If you would only like it to load a single model for prediction, then you should use `--checkpoint_path /path/to/model.pt`.
