### ISSUE TITLE
Replace hard-wired features with feature factory

### ISSUE THREAD

**Issue by joergkurtwegner** [wengong-jin/chemprop#12]
Hi, for enabling us to feed in easily other type of vectorial data without enforcing hard-coding in a deeper class/function, I replaced the existing logic by using fully the already existing feature factory.
This is also used in argparse and can therefore easily handle more extensions by just adding new modules to the feature factory.

Please check and let me know what you think
https://github.com/joergkurtwegner/chemprop/commit/0e14e539592e17f60dce8c73d13bbac58badb027

**Comment by swansonk14** [comment]
Fixed in https://github.com/swansonk14/chemprop/pull/4
