### ISSUE TITLE
The benchmark should use the same random seed to split train, valid and test data

### ISSUE THREAD

**Issue by shenwanxiang** [wengong-jin/chemprop#18]
As we know, the random seed in splitting the dataset has a large impact on the final performance of test set, So all of these dataset should be evaluate as same as the test set in deepchem/molnet, namely, you should split your dataset as deepchem does! not just by yourself

**Comment by wengong-jin** [comment]
This repo is deprecated, we did compare with molnet on EXACTLY the same train/valid/test split in our new repo here: https://github.com/swansonk14/chemprop#results
