### ISSUE TITLE
BCELoss is unstable

### ISSUE THREAD

**Issue by joergkurtwegner** [wengong-jin/chemprop#7]
The “BCELoss” is highly unstable and crashes chemprop with assert statements on cuda level, could you change this to “BCEWithLogitsLoss”

**Comment by swansonk14** [comment]
We've tried using BCELoss on a number of datasets and have never run into any problems. Are you having trouble with one of our datasets or with a different dataset? Also, do you know what the class balance is (i.e. percent of 1s vs 0s)? We have found that training is somewhat unstable when the classes are severely unbalanced (ex. 1% 1s and 99% 0s), but we've never seen assert statements on the cuda level.

By the way, we have deprecated this repo in favor of https://github.com/swansonk14/chemprop, in which we've significantly cleaned and simplified the code. Can you try the same experiments there? When we have time we will switch over from BCELoss to BCEWithLogitsLoss on that repo, but we don't plan to update this repo.

**Comment by swansonk14** [comment]
Actually I just switched from BCELoss to BCEWithLogitsLoss on https://github.com/swansonk14/chemprop. Hopefully that helps make training more stable.

**Comment by joergkurtwegner** [comment]
Thanks, Yes, I checked Tox21 with the partial charge addition (one of the open issues), I believe, it was surely one of the default data sets.
