### ISSUE TITLE
generalize FunctionalGroupFeaturizer

### ISSUE THREAD

**Issue by joergkurtwegner** [wengong-jin/chemprop#8]
Dear all, the SMARTS definition is hard to read and does not allow comments or any details.
Might I suggest to switch to the RDKit feature factory to make this more generic?

Find the class modification attached and please change the following command line parameters in parsing.py

    parser.add_argument('--additional_atom_features', type=str, nargs='*', choices=['smarts','family_and_type'], default=[],
                        help='Use additional features in atom featurization')
    parser.add_argument('--atom_features_family_and_type', type=str, default='{RDDataDir}/BaseFeatures.fdef',
                        help='Path to txt file of smarts for functional groups, if functional_group features are on.')
    parser.add_argument('--atom_features_smarts', type=str, default='chemprop/features/smarts.txt',
                        help='Path to txt file of smarts for functional groups, if functional_group features are on.')

[functional_groups.py.txt](https://github.com/wengong-jin/chemprop/files/2817917/functional_groups.py.txt)

**Comment by joergkurtwegner** [comment]
requires also a change in featurization.py

```
<         if 'functional_group' in args.additional_atom_features:
---
>         if ['smarts','family_and_type'] in args.additional_atom_features:
```

**Comment by swansonk14** [comment]
We've actually deprecated this repo in favor of https://github.com/swansonk14/chemprop, and in that new repo we removed SMARTS features since we didn't find them particularly helpful. Do you think it would be a useful feature to have? If so, we can consider implementing it in the new repo.
